from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def replace(path, old, new):
    file = ROOT / path
    text = file.read_text()
    if old not in text:
        raise RuntimeError(f"Expected text not found in {path}: {old[:120]!r}")
    file.write_text(text.replace(old, new, 1))

replace("server/corpus.js", '.select("session_id, participant_id, language, completed, completed_at, created_at, updated_at, last_activity_at, ended_at, session_status, end_reason, timed_out_at, continuation_of_session_id, inactivity_timeout_minutes, active_duration_ms, elapsed_duration_ms, inactivity_break_count, excluded_idle_duration_ms, inactivity_breaks, duration_calculated_at")', '.select("session_id, participant_id, language, completed, completed_at, created_at, updated_at, last_activity_at, ended_at, session_status, end_reason, timed_out_at, continuation_of_session_id, inactivity_timeout_minutes, active_duration_ms, elapsed_duration_ms, inactivity_break_count, excluded_idle_duration_ms, inactivity_breaks, duration_calculated_at, interview_model, research_design_id, research_designs(protocol_version, research_title)")')

replace("api/statistics.js", '        continuationOfSessionId:\n            lifecycle.continuationOfSessionId || null,\n        durationCalculatedAt: lifecycle.durationCalculatedAt || null', '        continuationOfSessionId:\n            lifecycle.continuationOfSessionId || null,\n        interviewModel: lifecycle.interviewModel || null,\n        researchDesignId: lifecycle.researchDesignId || null,\n        protocolVersion: lifecycle.protocolVersion || null,\n        researchTitle: lifecycle.researchTitle || null,\n        durationCalculatedAt: lifecycle.durationCalculatedAt || null')
replace("api/statistics.js", '                    durationCalculatedAt:\n                        row?.duration_calculated_at || null', '                    durationCalculatedAt:\n                        row?.duration_calculated_at || null,\n                    interviewModel: row?.interview_model || null,\n                    researchDesignId: row?.research_design_id || null,\n                    protocolVersion: row?.research_designs?.protocol_version || null,\n                    researchTitle: row?.research_designs?.research_title || null')
replace("api/statistics.js", '            durationCalculation: {\n                primaryMetric: "active_interview_duration",', '            interviewModels: [...new Set(\n                [...sessionSummaries.values()]\n                    .map(session => session.interviewModel)\n                    .filter(Boolean)\n            )].sort(),\n            protocolVersions: [...new Set(\n                [...sessionSummaries.values()]\n                    .map(session => session.protocolVersion)\n                    .filter(Boolean)\n            )].sort(),\n            durationCalculation: {\n                primaryMetric: "active_interview_duration",')
replace("api/statistics.js", '.select("session_id, language, completed, last_activity_at, ended_at, session_status, end_reason, timed_out_at, continuation_of_session_id, inactivity_timeout_minutes, active_duration_ms, elapsed_duration_ms, inactivity_break_count, excluded_idle_duration_ms, inactivity_breaks, duration_calculated_at")', '.select("session_id, language, completed, last_activity_at, ended_at, session_status, end_reason, timed_out_at, continuation_of_session_id, inactivity_timeout_minutes, active_duration_ms, elapsed_duration_ms, inactivity_break_count, excluded_idle_duration_ms, inactivity_breaks, duration_calculated_at, interview_model, research_design_id, research_designs(protocol_version, research_title)")')

replace("researcher.html", '    <p id="legacyNote" class="legacyNote" hidden></p>\n</section>', '    <h3>Interview conditions</h3>\n    <div class="tableScroll">\n        <table>\n            <thead><tr><th scope="col">Interview model</th><th scope="col">Protocol version</th><th scope="col">Sessions</th><th scope="col">Completed sessions</th><th scope="col">Messages</th></tr></thead>\n            <tbody id="conditionSummaryBody"></tbody>\n        </table>\n    </div>\n\n    <p id="legacyNote" class="legacyNote" hidden></p>\n</section>')
replace("researcher.html", '                <th scope="col">Participant</th>\n                <th scope="col">Messages</th>', '                <th scope="col">Participant</th>\n                <th scope="col">Interview model</th>\n                <th scope="col">Protocol version</th>\n                <th scope="col">Messages</th>')
replace("researcher.html", '            participantLabel(session.participants),\n            session.messageCount,', '            participantLabel(session.participants),\n            session.interviewModel || "Unknown / legacy",\n            session.protocolVersion || "Unknown / legacy",\n            session.messageCount,')
replace("researcher.html", '    const legacyNote = document.getElementById("legacyNote");', '    const conditionBody = document.getElementById("conditionSummaryBody");\n    conditionBody.replaceChildren();\n    const conditions = new Map();\n    data.languages.flatMap(language => language.sessions).forEach(session => {\n        const model = session.interviewModel || "Unknown / legacy";\n        const version = session.protocolVersion || "Unknown / legacy";\n        const key = `${model}\\u0000${version}`;\n        if (!conditions.has(key)) conditions.set(key, { model, version, sessions: 0, completed: 0, messages: 0 });\n        const condition = conditions.get(key);\n        condition.sessions += 1;\n        condition.completed += session.completed ? 1 : 0;\n        condition.messages += session.messageCount;\n    });\n    [...conditions.values()].sort((a, b) => a.model.localeCompare(b.model) || a.version.localeCompare(b.version)).forEach(condition => {\n        const row = document.createElement("tr");\n        [condition.model, condition.version, condition.sessions, condition.completed, condition.messages].forEach(value => {\n            const cell = document.createElement("td"); cell.textContent = value; row.appendChild(cell);\n        });\n        conditionBody.appendChild(row);\n    });\n\n    const legacyNote = document.getElementById("legacyNote");')
replace("researcher.html", '    document.getElementById("transcriptHeading").textContent =\n        `Session ${sessionId} — Transcript`;', '    const sessionMetadata = statistics?.languages.flatMap(language => language.sessions).find(session => session.session === sessionId);\n    const conditionLabel = sessionMetadata ? ` — ${sessionMetadata.interviewModel || "Unknown model"} · Protocol ${sessionMetadata.protocolVersion || "unknown"}` : "";\n    document.getElementById("transcriptHeading").textContent =\n        `Session ${sessionId} — Transcript${conditionLabel}`;')

replace("api/analysis.js", '        timedOutAt: session?.timed_out_at || null,\n        descriptors: descriptor ? {', '        timedOutAt: session?.timed_out_at || null,\n        interviewModel: session?.interview_model || null,\n        researchDesignId: session?.research_design_id || null,\n        protocolVersion: session?.research_designs?.protocol_version || null,\n        researchTitle: session?.research_designs?.research_title || null,\n        descriptors: descriptor ? {')
replace("api/analysis.js", '.select("session_id, participant_id, language, completed, completed_at, session_status, end_reason, timed_out_at")', '.select("session_id, participant_id, language, completed, completed_at, session_status, end_reason, timed_out_at, interview_model, research_design_id, research_designs(protocol_version, research_title)")')
replace("api/analysis.js", '    const sessions = new Set(\n        prepared.messages.map(message => message.sessionId).filter(Boolean)\n    );', '    const sessions = new Set(\n        prepared.messages.map(message => message.sessionId).filter(Boolean)\n    );\n    const representedSessionRows = eligibleSessions.filter(session => sessions.has(session.session_id));\n    const interviewModels = [...new Set(representedSessionRows.map(session => session.interview_model).filter(Boolean))].sort();\n    const protocolVersions = [...new Set(representedSessionRows.map(session => session.research_designs?.protocol_version).filter(Boolean))].sort();\n    const researchDesignIds = [...new Set(representedSessionRows.map(session => session.research_design_id).filter(Boolean))];')
replace("api/analysis.js", '            model,\n            analysis_version: QUALITATIVE_ANALYSIS_VERSION,', '            model,\n            interview_models: interviewModels,\n            protocol_versions: protocolVersions,\n            research_design_ids: researchDesignIds,\n            analysis_version: QUALITATIVE_ANALYSIS_VERSION,')
replace("api/analysis.js", '            timedOutAt: session.timedOutAt,\n            descriptors: session.descriptors,', '            timedOutAt: session.timedOutAt,\n            interviewModel: session.interviewModel,\n            researchDesignId: session.researchDesignId,\n            protocolVersion: session.protocolVersion,\n            researchTitle: session.researchTitle,\n            descriptors: session.descriptors,')

replace("researcher-analysis.js", '            appendTextBlock(article, "Language", session.language);\n            appendTextBlock(\n                article,\n                "Session status",', '            appendTextBlock(article, "Language", session.language);\n            appendTextBlock(article, "Interview model", session.interviewModel || "Unknown / legacy");\n            appendTextBlock(article, "Protocol version", session.protocolVersion || "Unknown / legacy");\n            appendTextBlock(\n                article,\n                "Session status",')
replace("researcher-analysis.js", '            appendTextBlock(article, "Language", session.language);\n            appendTextBlock(\n                article,\n                "Completion status",', '            appendTextBlock(article, "Language", session.language);\n            appendTextBlock(article, "Interview model", session.interviewModel || "Unknown / legacy");\n            appendTextBlock(article, "Protocol version", session.protocolVersion || "Unknown / legacy");\n            appendTextBlock(\n                article,\n                "Completion status",')
replace("researcher-analysis.js", '            option.textContent = `${new Date(run.created_at).toLocaleString()} — ${run.model} — ${run.status}`;', '            const interviewCondition = (run.interview_models || []).length === 1 ? run.interview_models[0] : (run.interview_models || []).length ? "mixed interview models" : "unknown interview model";\n            option.textContent = `${new Date(run.created_at).toLocaleString()} — interview ${interviewCondition} — analysis ${run.model} — ${run.status}`;')
replace("researcher-analysis.js", '            `Model ${workspace.run.model}`,\n            `${workspace.run.messages_analyzed} participant messages analysed`,', '            `Interview model${(workspace.run.interview_models || []).length === 1 ? "" : "s"}: ${(workspace.run.interview_models || []).join(", ") || "Unknown / legacy"}`,\n            `Protocol version${(workspace.run.protocol_versions || []).length === 1 ? "" : "s"}: ${(workspace.run.protocol_versions || []).join(", ") || "Unknown / legacy"}`,\n            `Analysis model: ${workspace.run.model}`,\n            `${workspace.run.messages_analyzed} participant messages analysed`,')

(ROOT / "supabase/migrations/20260719070000_add_analysis_interview_condition_provenance.sql").write_text("""alter table public.qualitative_analysis_runs
  add column if not exists interview_models text[] not null default '{}',
  add column if not exists protocol_versions text[] not null default '{}',
  add column if not exists research_design_ids uuid[] not null default '{}';

comment on column public.qualitative_analysis_runs.interview_models is
  'Frozen set of interview-model IDs represented in this analysis run corpus.';
comment on column public.qualitative_analysis_runs.protocol_versions is
  'Frozen set of researcher-defined protocol versions represented in this analysis run corpus.';
comment on column public.qualitative_analysis_runs.research_design_ids is
  'Frozen set of exact research-design row IDs represented in this analysis run corpus.';
""")

print("Dashboard interview-model provenance patch applied.")
