import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { handleMessages } from "../api/messages.js";
import { loadParticipantCodeMap } from "../server/participantCodes.js";

const migration = await readFile(new URL(
    "../supabase/migrations/20260827070012_add_private_participant_codes.sql",
    import.meta.url
), "utf8");
const analysisApi = await readFile(
    new URL("../api/analysis.js", import.meta.url),
    "utf8"
);

function responseRecorder() {
    return {
        statusCode: null,
        payload: null,
        status(value) {
            this.statusCode = value;
            return this;
        },
        json(value) {
            this.payload = value;
            return this;
        }
    };
}

function transcriptClient(messages, codeRows = []) {
    return {
        from(table) {
            if (table === "interview_messages") {
                const query = {
                    select() {
                        return query;
                    },
                    eq() {
                        return query;
                    },
                    async order() {
                        return { data: messages, error: null };
                    }
                };
                return query;
            }

            assert.equal(table, "participant_code_map");
            const query = {
                select() {
                    return query;
                },
                async in() {
                    return { data: codeRows, error: null };
                }
            };
            return query;
        }
    };
}

const verifiedMessages = [
    {
        id: "message-1",
        Participant: "source-participant-id",
        Speaker: "Participant",
        Message: "I wake up early.",
        Timestamp: "2026-08-27T01:00:00.000Z",
        Language: "en",
        EnglishTranslation: null
    }
];

test("participant code mapping is private, stable, and auto-populated", () => {
    assert.match(migration, /create table public\.participant_code_map/);
    assert.match(migration, /generated by default as identity/);
    assert.match(migration, /'P' \|\| lpad\(code_number::text, 4, '0'\)/);
    assert.match(migration, /enable row level security/);
    assert.match(
        migration,
        /revoke all on table public\.participant_code_map\s+from public, anon, authenticated, service_role/
    );
    assert.match(migration, /grant select, insert on table public\.participant_code_map\s+to service_role/);
    assert.match(migration, /interview_sessions_ensure_participant_code/);
});

test("analysis payloads carry participant codes for rows and provenance", () => {
    assert.match(analysisApi, /loadParticipantCodeMap/);
    assert.match(analysisApi, /participantCodeById/);
    assert.match(analysisApi, /participantCode:\s*session\.participantCode/);
});

test("participant code loader returns only the protected mapping", async () => {
    const mapping = await loadParticipantCodeMap(
        transcriptClient([], [{
            participant_id: "source-participant-id",
            participant_code: "P0001"
        }]),
        ["source-participant-id", "source-participant-id"]
    );

    assert.equal(mapping.size, 1);
    assert.equal(mapping.get("source-participant-id"), "P0001");
});

test("transcript endpoint requires researcher authorization", async () => {
    const response = responseRecorder();
    let databaseRead = false;
    const client = {
        from() {
            databaseRead = true;
            throw new Error("must not read");
        }
    };

    await handleMessages(
        { query: { session: "session-1" }, headers: {} },
        response,
        {
            supabaseClient: client,
            openaiClient: null,
            configuredToken: "researcher-token"
        }
    );

    assert.equal(response.statusCode, 401);
    assert.equal(databaseRead, false);
});

test("transcript endpoint returns a verifiable code, source ID, and session", async () => {
    const response = responseRecorder();
    const client = transcriptClient(verifiedMessages, [{
        participant_id: "source-participant-id",
        participant_code: "P0001"
    }]);

    await handleMessages(
        {
            query: { session: "session-1" },
            headers: { authorization: "Bearer researcher-token" }
        },
        response,
        {
            supabaseClient: client,
            openaiClient: null,
            configuredToken: "researcher-token"
        }
    );

    assert.equal(response.statusCode, 200);
    assert.deepEqual(response.payload.identity, {
        sessionId: "session-1",
        participantId: "source-participant-id",
        participantCode: "P0001"
    });
    assert.equal(response.payload.messages.length, 1);
    assert.equal("Participant" in response.payload.messages[0], false);
});

test("transcript endpoint refuses ambiguous participant identity", async () => {
    const response = responseRecorder();
    const client = transcriptClient([
        verifiedMessages[0],
        { ...verifiedMessages[0], id: "message-2", Participant: "other-id" }
    ]);

    await handleMessages(
        {
            query: { session: "session-1" },
            headers: { authorization: "Bearer researcher-token" }
        },
        response,
        {
            supabaseClient: client,
            openaiClient: null,
            configuredToken: "researcher-token"
        }
    );

    assert.equal(response.statusCode, 409);
    assert.match(response.payload.error, /identity could not be verified/);
});
