-- Future Stage 1 reports must carry participant information produced inside
-- the same researcher-selected provider response as the case-bound analysis.
-- The current 275-case pilot is explicitly exempt because its immutable
-- GPT-5.6 responses predate this output field. Its participant worksheet may
-- use separately stored descriptive facts, including an explicitly
-- researcher-authorized GPT-5.1 demographic-only recovery source. No prior
-- analytical output is admitted by this exception.

create function public.stage1_participant_information_complete_v2(
    p_report jsonb
)
returns boolean
language plpgsql
immutable
security invoker
set search_path = ''
as $function$
declare
    information jsonb := p_report -> 'participant_information';
    field_name text;
    entry jsonb;
    source jsonb;
begin
    if jsonb_typeof(information) <> 'object' then return false; end if;

    foreach field_name in array array[
        'current_country', 'current_region', 'country_of_origin',
        'diaspora_status', 'gender', 'age', 'birth_year', 'birth_cohort',
        'youth_status', 'occupation', 'education_level', 'social_identity'
    ] loop
        entry := information -> field_name;
        if jsonb_typeof(entry) <> 'object'
           or not (entry ? 'value')
           or jsonb_typeof(entry -> 'sources') <> 'array' then
            return false;
        end if;

        if field_name in ('age', 'birth_year') then
            if jsonb_typeof(entry -> 'value') not in ('number', 'null') then
                return false;
            end if;
        elsif jsonb_typeof(entry -> 'value') not in ('string', 'null') then
            return false;
        end if;

        if jsonb_typeof(entry -> 'value') = 'null' then
            if jsonb_array_length(entry -> 'sources') <> 0 then
                return false;
            end if;
        elsif jsonb_array_length(entry -> 'sources') = 0 then
            return false;
        end if;

        for source in select value
            from jsonb_array_elements(entry -> 'sources')
        loop
            if jsonb_typeof(source) <> 'object'
               or nullif(btrim(source ->> 'turn_id'), '') is null
               or nullif(btrim(source ->> 'message_id'), '') is null
               or nullif(btrim(source ->> 'english_text'), '') is null then
                return false;
            end if;
        end loop;
    end loop;

    if jsonb_typeof(information -> 'additional_descriptors') <> 'array' then
        return false;
    end if;
    for entry in select value from jsonb_array_elements(
        information -> 'additional_descriptors'
    ) loop
        if jsonb_typeof(entry) <> 'object'
           or nullif(btrim(entry ->> 'name'), '') is null
           or nullif(btrim(entry ->> 'value'), '') is null
           or jsonb_typeof(entry -> 'sources') <> 'array'
           or jsonb_array_length(entry -> 'sources') = 0 then
            return false;
        end if;
        for source in select value
            from jsonb_array_elements(entry -> 'sources')
        loop
            if jsonb_typeof(source) <> 'object'
               or nullif(btrim(source ->> 'turn_id'), '') is null
               or nullif(btrim(source ->> 'message_id'), '') is null
               or nullif(btrim(source ->> 'english_text'), '') is null then
                return false;
            end if;
        end loop;
    end loop;

    return true;
end;
$function$;

revoke all on function public.stage1_participant_information_complete_v2(jsonb)
from public, anon, authenticated;
grant execute on function public.stage1_participant_information_complete_v2(jsonb)
to service_role;

alter table public.stage1_readable_reports_v2
    add constraint stage1_readable_reports_v2_future_participant_information
    check (
        source_kind = 'frozen_gpt56_response_projection'
        or public.stage1_participant_information_complete_v2(report_json)
    );

comment on constraint
    stage1_readable_reports_v2_future_participant_information
on public.stage1_readable_reports_v2 is
    'Future provider-completed Stage 1 reports include transcript-supported participant information generated by the same selected model in the same single response. The frozen GPT-5.6 pilot fixture is exempt and may use demographic-only recovery without inheriting prior analytical work.';
