create table if not exists public.advanced_preliminary_analysis_runs (
    id uuid primary key default gen_random_uuid(),
    run_number bigint generated by default as identity unique not null,
    status text not null default 'queued'
        check (status in (
            'queued', 'processing', 'completed',
            'completed_with_failures', 'cancelled', 'failed'
        )),
    source_scope text not null default 'all_formally_completed_transcripts'
        check (source_scope = 'all_formally_completed_transcripts'),
    provider text not null,
    model text not null,
    resolved_model text,
    reasoning_effort text not null
        check (reasoning_effort in ('low', 'medium', 'high', 'xhigh', 'max')),
    analysis_version text not null,
    prompt_version text not null,
    prior_analysis_role text not null default 'preserved_preliminary_comparison',
    stop_layer text not null default 'preliminary_categories'
        check (stop_layer = 'preliminary_categories'),
    project_snapshot jsonb not null default '[]'::jsonb,
    source_case_count integer not null default 0 check (source_case_count >= 0),
    pending_count integer not null default 0 check (pending_count >= 0),
    processing_count integer not null default 0 check (processing_count >= 0),
    completed_count integer not null default 0 check (completed_count >= 0),
    failed_count integer not null default 0 check (failed_count >= 0),
    requested_by text not null default 'researcher',
    requested_at timestamptz not null default now(),
    model_verified_at timestamptz,
    started_at timestamptz,
    completed_at timestamptz,
    cancelled_at timestamptz,
    cancellation_reason text,
    updated_at timestamptz not null default now(),
    last_error text,
    constraint advanced_preliminary_run_identity_nonempty check (
        btrim(provider) <> ''
        and btrim(model) <> ''
        and btrim(analysis_version) <> ''
        and btrim(prompt_version) <> ''
    )
);

comment on table public.advanced_preliminary_analysis_runs is
    'Versioned, dataset-wide advanced preliminary analyses generated only from preserved transcripts. Existing preliminary reports remain unchanged and are never used as analytical input.';

create table if not exists public.advanced_preliminary_analysis_jobs (
    id uuid primary key default gen_random_uuid(),
    run_id uuid not null
        references public.advanced_preliminary_analysis_runs(id) on delete restrict,
    session_id text not null references public.interview_sessions(session_id) on delete restrict,
    participant_id text not null,
    case_number text not null,
    source_completed_at timestamptz not null,
    project_id uuid references public.research_projects(id) on delete restrict,
    analysis_framework_id uuid references public.analysis_frameworks(id) on delete restrict,
    source_report_id uuid references public.qualitative_case_reports(id) on delete restrict,
    project_binding_status text not null
        check (project_binding_status in ('project_bound', 'historical_unbound')),
    status text not null default 'pending'
        check (status in ('pending', 'processing', 'completed', 'failed', 'cancelled')),
    attempt_count integer not null default 0 check (attempt_count >= 0),
    queued_at timestamptz not null default now(),
    claimed_at timestamptz,
    lease_expires_at timestamptz,
    next_retry_at timestamptz,
    completed_at timestamptz,
    updated_at timestamptz not null default now(),
    last_error text,
    unique (run_id, session_id)
);

create index if not exists advanced_preliminary_jobs_fifo_idx
on public.advanced_preliminary_analysis_jobs (
    run_id, status, source_completed_at, session_id
);

create index if not exists advanced_preliminary_jobs_session_idx
on public.advanced_preliminary_analysis_jobs (session_id);

create index if not exists advanced_preliminary_jobs_project_idx
on public.advanced_preliminary_analysis_jobs (project_id)
where project_id is not null;

create index if not exists advanced_preliminary_jobs_framework_idx
on public.advanced_preliminary_analysis_jobs (analysis_framework_id)
where analysis_framework_id is not null;

create index if not exists advanced_preliminary_jobs_source_report_idx
on public.advanced_preliminary_analysis_jobs (source_report_id)
where source_report_id is not null;

create table if not exists public.advanced_preliminary_case_reports (
    id uuid primary key default gen_random_uuid(),
    run_id uuid not null
        references public.advanced_preliminary_analysis_runs(id) on delete restrict,
    job_id uuid not null unique
        references public.advanced_preliminary_analysis_jobs(id) on delete restrict,
    session_id text not null references public.interview_sessions(session_id) on delete restrict,
    case_number text not null,
    participant_id text not null,
    participant_code text,
    language text,
    project_id uuid references public.research_projects(id) on delete restrict,
    analysis_framework_id uuid references public.analysis_frameworks(id) on delete restrict,
    source_report_id uuid references public.qualitative_case_reports(id) on delete restrict,
    provider text not null,
    model text not null,
    resolved_model text,
    reasoning_effort text not null,
    analysis_version text not null,
    prompt_version text not null,
    case_summary text not null,
    unassigned_code_numbers jsonb not null default '[]'::jsonb,
    analytical_audit jsonb not null default '{}'::jsonb,
    input_token_count integer,
    output_token_count integer,
    created_at timestamptz not null default now(),
    completed_at timestamptz not null default now(),
    unique (run_id, session_id)
);

comment on table public.advanced_preliminary_case_reports is
    'New preliminary case-analysis versions ending at categories. They are comparisons, not replacements for qualitative_case_reports.';

create index if not exists advanced_preliminary_reports_project_idx
on public.advanced_preliminary_case_reports (project_id)
where project_id is not null;

create index if not exists advanced_preliminary_reports_framework_idx
on public.advanced_preliminary_case_reports (analysis_framework_id)
where analysis_framework_id is not null;

create index if not exists advanced_preliminary_reports_source_report_idx
on public.advanced_preliminary_case_reports (source_report_id)
where source_report_id is not null;

create table if not exists public.advanced_preliminary_meaning_units (
    id uuid primary key default gen_random_uuid(),
    report_id uuid not null
        references public.advanced_preliminary_case_reports(id) on delete restrict,
    unit_number integer not null check (unit_number > 0),
    message_id uuid not null references public.interview_messages(id) on delete restrict,
    exact_source_text text not null,
    source_language text,
    start_offset integer not null check (start_offset >= 0),
    end_offset integer not null check (end_offset > start_offset),
    occurrence_index integer not null default 1 check (occurrence_index > 0),
    context_note text,
    created_at timestamptz not null default now(),
    unique (report_id, unit_number),
    unique (report_id, message_id, start_offset, end_offset)
);

comment on table public.advanced_preliminary_meaning_units is
    'Case-grounded original-language transcript spans. Meaning units are never standardized across cases.';

create index if not exists advanced_preliminary_mu_message_idx
on public.advanced_preliminary_meaning_units (message_id);

create table if not exists public.advanced_preliminary_codes (
    id uuid primary key default gen_random_uuid(),
    report_id uuid not null
        references public.advanced_preliminary_case_reports(id) on delete restrict,
    code_number integer not null check (code_number > 0),
    code_label text not null,
    definition text not null,
    rationale text not null,
    meaning_unit_count integer not null check (meaning_unit_count > 0),
    occurrence_count integer not null check (occurrence_count > 0),
    created_at timestamptz not null default now(),
    unique (report_id, code_number)
);

create table if not exists public.advanced_preliminary_code_meaning_units (
    report_id uuid not null
        references public.advanced_preliminary_case_reports(id) on delete restrict,
    code_id uuid not null
        references public.advanced_preliminary_codes(id) on delete restrict,
    meaning_unit_id uuid not null
        references public.advanced_preliminary_meaning_units(id) on delete restrict,
    created_at timestamptz not null default now(),
    primary key (code_id, meaning_unit_id)
);

create index if not exists advanced_preliminary_code_mu_report_idx
on public.advanced_preliminary_code_meaning_units (report_id);

create index if not exists advanced_preliminary_code_mu_unit_idx
on public.advanced_preliminary_code_meaning_units (meaning_unit_id);

create table if not exists public.advanced_preliminary_categories (
    id uuid primary key default gen_random_uuid(),
    report_id uuid not null
        references public.advanced_preliminary_case_reports(id) on delete restrict,
    category_number integer not null check (category_number > 0),
    category_label text not null,
    definition text not null,
    rationale text not null,
    code_count integer not null check (code_count >= 2),
    created_at timestamptz not null default now(),
    unique (report_id, category_number)
);

create table if not exists public.advanced_preliminary_category_codes (
    report_id uuid not null
        references public.advanced_preliminary_case_reports(id) on delete restrict,
    category_id uuid not null
        references public.advanced_preliminary_categories(id) on delete restrict,
    code_id uuid not null
        references public.advanced_preliminary_codes(id) on delete restrict,
    created_at timestamptz not null default now(),
    primary key (category_id, code_id),
    unique (report_id, code_id)
);

create index if not exists advanced_preliminary_category_code_report_idx
on public.advanced_preliminary_category_codes (report_id);

create or replace function public.refresh_advanced_preliminary_analysis_run(
    p_run_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    counts record;
begin
    select
        count(*) filter (
            where status = 'pending'
               or (status = 'failed' and attempt_count < 3 and next_retry_at is not null)
        )::integer as pending_count,
        count(*) filter (where status = 'processing')::integer as processing_count,
        count(*) filter (where status = 'completed')::integer as completed_count,
        count(*) filter (
            where status = 'failed'
              and (attempt_count >= 3 or next_retry_at is null)
        )::integer as failed_count,
        count(*)::integer as total_count
    into counts
    from public.advanced_preliminary_analysis_jobs
    where run_id = p_run_id;

    update public.advanced_preliminary_analysis_runs
    set pending_count = counts.pending_count,
        processing_count = counts.processing_count,
        completed_count = counts.completed_count,
        failed_count = counts.failed_count,
        status = case
            when cancelled_at is not null then 'cancelled'
            when counts.total_count = 0 then 'failed'
            when counts.pending_count = 0 and counts.processing_count = 0
                then case when counts.failed_count > 0
                    then 'completed_with_failures' else 'completed' end
            when counts.processing_count > 0 or counts.completed_count > 0
                then 'processing'
            else 'queued'
        end,
        started_at = case
            when counts.processing_count > 0 or counts.completed_count > 0
                then coalesce(started_at, now())
            else started_at
        end,
        completed_at = case
            when counts.pending_count = 0 and counts.processing_count = 0
                and counts.total_count > 0 then coalesce(completed_at, now())
            else null
        end,
        updated_at = now()
    where id = p_run_id;
end;
$$;

create or replace function public.create_advanced_preliminary_analysis_run(
    p_provider text,
    p_model text,
    p_resolved_model text,
    p_reasoning_effort text,
    p_analysis_version text,
    p_prompt_version text,
    p_requested_by text default 'researcher'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
    new_run_id uuid;
begin
    perform pg_advisory_xact_lock(hashtext('advanced_preliminary_analysis_run'));

    if exists (
        select 1 from public.advanced_preliminary_analysis_runs
        where status in ('queued', 'processing')
    ) then
        raise exception 'An advanced preliminary analysis run is already active.';
    end if;

    if btrim(coalesce(p_provider, '')) = ''
       or btrim(coalesce(p_model, '')) = ''
       or btrim(coalesce(p_resolved_model, '')) = ''
       or btrim(coalesce(p_analysis_version, '')) = ''
       or btrim(coalesce(p_prompt_version, '')) = '' then
        raise exception 'Model and version provenance are required.';
    end if;

    insert into public.advanced_preliminary_analysis_runs (
        provider, model, resolved_model, reasoning_effort,
        analysis_version, prompt_version, requested_by,
        model_verified_at, project_snapshot
    )
    values (
        btrim(p_provider), btrim(p_model), btrim(p_resolved_model),
        p_reasoning_effort, btrim(p_analysis_version), btrim(p_prompt_version),
        coalesce(nullif(btrim(p_requested_by), ''), 'researcher'), now(),
        coalesce((
            select jsonb_agg(project_record order by project_record->>'project_name')
            from (
                select distinct jsonb_build_object(
                    'project_id', project.id,
                    'project_code', project.project_code,
                    'project_name', project.project_name,
                    'research_topic', project.research_topic
                ) as project_record
                from public.research_projects as project
                join public.research_designs as design on design.project_id = project.id
                join public.interview_sessions as session on session.research_design_id = design.id
                where session.completed = true and session.completed_at is not null
            ) as projects
        ), '[]'::jsonb)
    )
    returning id into new_run_id;

    insert into public.advanced_preliminary_analysis_jobs (
        run_id, session_id, participant_id, case_number,
        source_completed_at, project_id, analysis_framework_id,
        source_report_id, project_binding_status
    )
    select
        new_run_id,
        session.session_id,
        session.participant_id,
        job.case_number,
        session.completed_at,
        job.project_id,
        job.analysis_framework_id,
        report.id,
        case when job.project_id is null
            then 'historical_unbound' else 'project_bound' end
    from public.interview_sessions as session
    join public.automatic_case_analysis_jobs as job
      on job.session_id = session.session_id
    left join lateral (
        select candidate.id
        from public.qualitative_case_reports as candidate
        where candidate.session_id = session.session_id
          and candidate.superseded_at is null
        order by candidate.completed_at desc, candidate.created_at desc
        limit 1
    ) as report on true
    where session.completed = true
      and session.completed_at is not null
    order by session.completed_at, session.session_id;

    update public.advanced_preliminary_analysis_runs
    set source_case_count = (
            select count(*) from public.advanced_preliminary_analysis_jobs
            where run_id = new_run_id
        ),
        pending_count = (
            select count(*) from public.advanced_preliminary_analysis_jobs
            where run_id = new_run_id and status = 'pending'
        ),
        updated_at = now()
    where id = new_run_id;

    return new_run_id;
end;
$$;

create or replace function public.claim_next_advanced_preliminary_analysis()
returns table (
    job_id uuid,
    run_id uuid,
    session_id text,
    participant_id text,
    case_number text,
    source_completed_at timestamptz,
    project_id uuid,
    analysis_framework_id uuid,
    source_report_id uuid,
    project_binding_status text,
    provider text,
    model text,
    resolved_model text,
    reasoning_effort text,
    analysis_version text,
    prompt_version text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    selected_job public.advanced_preliminary_analysis_jobs%rowtype;
begin
    perform pg_advisory_xact_lock(hashtext('advanced_preliminary_analysis_worker'));

    update public.advanced_preliminary_analysis_jobs
    set status = 'failed',
        lease_expires_at = null,
        next_retry_at = now(),
        last_error = coalesce(last_error, 'Worker lease expired; retry scheduled.'),
        updated_at = now()
    where status = 'processing'
      and lease_expires_at < now();

    perform public.refresh_advanced_preliminary_analysis_run(run.id)
    from public.advanced_preliminary_analysis_runs as run
    where run.status in ('queued', 'processing');

    if exists (
        select 1 from public.advanced_preliminary_analysis_jobs
        where status = 'processing' and lease_expires_at >= now()
    ) then
        return;
    end if;

    select candidate.* into selected_job
    from public.advanced_preliminary_analysis_jobs as candidate
    join public.advanced_preliminary_analysis_runs as run on run.id = candidate.run_id
    where run.status in ('queued', 'processing')
      and (
        candidate.status = 'pending'
        or (
            candidate.status = 'failed'
            and candidate.attempt_count < 3
            and coalesce(candidate.next_retry_at, '-infinity'::timestamptz) <= now()
        )
      )
    order by run.requested_at, candidate.source_completed_at, candidate.session_id
    for update of candidate skip locked
    limit 1;

    if selected_job.id is null then
        return;
    end if;

    update public.advanced_preliminary_analysis_jobs
    set status = 'processing',
        attempt_count = attempt_count + 1,
        claimed_at = now(),
        lease_expires_at = now() + interval '12 minutes',
        next_retry_at = null,
        updated_at = now()
    where id = selected_job.id;

    perform public.refresh_advanced_preliminary_analysis_run(selected_job.run_id);

    return query
    select
        selected_job.id,
        selected_job.run_id,
        selected_job.session_id,
        selected_job.participant_id,
        selected_job.case_number,
        selected_job.source_completed_at,
        selected_job.project_id,
        selected_job.analysis_framework_id,
        selected_job.source_report_id,
        selected_job.project_binding_status,
        run.provider,
        run.model,
        run.resolved_model,
        run.reasoning_effort,
        run.analysis_version,
        run.prompt_version
    from public.advanced_preliminary_analysis_runs as run
    where run.id = selected_job.run_id;
end;
$$;

create or replace function public.complete_advanced_preliminary_analysis(
    p_job_id uuid,
    p_participant_code text,
    p_language text,
    p_input_token_count integer,
    p_output_token_count integer,
    p_payload jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
    selected_job public.advanced_preliminary_analysis_jobs%rowtype;
    selected_run public.advanced_preliminary_analysis_runs%rowtype;
    new_report_id uuid;
    item jsonb;
    item_number integer;
    new_code_id uuid;
    new_category_id uuid;
begin
    select * into selected_job
    from public.advanced_preliminary_analysis_jobs
    where id = p_job_id
    for update;

    if selected_job.id is null or selected_job.status <> 'processing' then
        raise exception 'The advanced preliminary job is not processing.';
    end if;

    select * into selected_run
    from public.advanced_preliminary_analysis_runs
    where id = selected_job.run_id;

    insert into public.advanced_preliminary_case_reports (
        run_id, job_id, session_id, case_number, participant_id,
        participant_code, language, project_id, analysis_framework_id,
        source_report_id, provider, model, resolved_model, reasoning_effort,
        analysis_version, prompt_version, case_summary,
        unassigned_code_numbers, analytical_audit,
        input_token_count, output_token_count
    ) values (
        selected_job.run_id, selected_job.id, selected_job.session_id,
        selected_job.case_number, selected_job.participant_id,
        nullif(btrim(p_participant_code), ''), nullif(btrim(p_language), ''),
        selected_job.project_id, selected_job.analysis_framework_id,
        selected_job.source_report_id, selected_run.provider,
        selected_run.model, selected_run.resolved_model,
        selected_run.reasoning_effort, selected_run.analysis_version,
        selected_run.prompt_version, p_payload->>'caseSummary',
        coalesce(p_payload->'unassignedCodeNumbers', '[]'::jsonb),
        coalesce(p_payload->'audit', '{}'::jsonb),
        p_input_token_count, p_output_token_count
    ) returning id into new_report_id;

    for item, item_number in
        select value, ordinality::integer
        from jsonb_array_elements(p_payload->'meaningUnits') with ordinality
    loop
        insert into public.advanced_preliminary_meaning_units (
            report_id, unit_number, message_id, exact_source_text,
            source_language, start_offset, end_offset, occurrence_index,
            context_note
        ) values (
            new_report_id, item_number, (item->>'messageId')::uuid,
            item->>'exactSourceText', item->>'sourceLanguage',
            (item->>'startOffset')::integer, (item->>'endOffset')::integer,
            (item->>'occurrenceIndex')::integer, item->>'contextNote'
        );
    end loop;

    for item, item_number in
        select value, ordinality::integer
        from jsonb_array_elements(p_payload->'codes') with ordinality
    loop
        insert into public.advanced_preliminary_codes (
            report_id, code_number, code_label, definition, rationale,
            meaning_unit_count, occurrence_count
        ) values (
            new_report_id, item_number, item->>'label', item->>'definition',
            item->>'rationale', jsonb_array_length(item->'meaningUnitNumbers'),
            jsonb_array_length(item->'meaningUnitNumbers')
        ) returning id into new_code_id;

        insert into public.advanced_preliminary_code_meaning_units (
            report_id, code_id, meaning_unit_id
        )
        select new_report_id, new_code_id, meaning_unit.id
        from jsonb_array_elements_text(item->'meaningUnitNumbers') as number(value)
        join public.advanced_preliminary_meaning_units as meaning_unit
          on meaning_unit.report_id = new_report_id
         and meaning_unit.unit_number = number.value::integer;
    end loop;

    for item, item_number in
        select value, ordinality::integer
        from jsonb_array_elements(p_payload->'categories') with ordinality
    loop
        insert into public.advanced_preliminary_categories (
            report_id, category_number, category_label, definition,
            rationale, code_count
        ) values (
            new_report_id, item_number, item->>'label', item->>'definition',
            item->>'rationale', jsonb_array_length(item->'codeNumbers')
        ) returning id into new_category_id;

        insert into public.advanced_preliminary_category_codes (
            report_id, category_id, code_id
        )
        select new_report_id, new_category_id, code.id
        from jsonb_array_elements_text(item->'codeNumbers') as number(value)
        join public.advanced_preliminary_codes as code
          on code.report_id = new_report_id
         and code.code_number = number.value::integer;
    end loop;

    update public.advanced_preliminary_analysis_jobs
    set status = 'completed', completed_at = now(), lease_expires_at = null,
        next_retry_at = null, last_error = null, updated_at = now()
    where id = selected_job.id;

    perform public.refresh_advanced_preliminary_analysis_run(selected_job.run_id);
    return new_report_id;
end;
$$;

create or replace function public.fail_advanced_preliminary_analysis(
    p_job_id uuid,
    p_error text,
    p_retryable boolean default true
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    selected_job public.advanced_preliminary_analysis_jobs%rowtype;
begin
    select * into selected_job
    from public.advanced_preliminary_analysis_jobs
    where id = p_job_id
    for update;

    if selected_job.id is null then return; end if;

    update public.advanced_preliminary_analysis_jobs
    set status = 'failed',
        lease_expires_at = null,
        next_retry_at = case
            when p_retryable and attempt_count < 3
                then now() + make_interval(
                    mins => least(20, power(2, attempt_count)::integer)
                )
            else null
        end,
        last_error = left(coalesce(p_error, 'Unknown analysis failure.'), 5000),
        updated_at = now()
    where id = selected_job.id;

    perform public.refresh_advanced_preliminary_analysis_run(selected_job.run_id);
end;
$$;

alter table public.advanced_preliminary_analysis_runs enable row level security;
alter table public.advanced_preliminary_analysis_jobs enable row level security;
alter table public.advanced_preliminary_case_reports enable row level security;
alter table public.advanced_preliminary_meaning_units enable row level security;
alter table public.advanced_preliminary_codes enable row level security;
alter table public.advanced_preliminary_code_meaning_units enable row level security;
alter table public.advanced_preliminary_categories enable row level security;
alter table public.advanced_preliminary_category_codes enable row level security;

revoke all on table public.advanced_preliminary_analysis_runs from anon, authenticated;
revoke all on table public.advanced_preliminary_analysis_jobs from anon, authenticated;
revoke all on table public.advanced_preliminary_case_reports from anon, authenticated;
revoke all on table public.advanced_preliminary_meaning_units from anon, authenticated;
revoke all on table public.advanced_preliminary_codes from anon, authenticated;
revoke all on table public.advanced_preliminary_code_meaning_units from anon, authenticated;
revoke all on table public.advanced_preliminary_categories from anon, authenticated;
revoke all on table public.advanced_preliminary_category_codes from anon, authenticated;

grant select on table public.advanced_preliminary_analysis_runs to service_role;
grant select on table public.advanced_preliminary_analysis_jobs to service_role;
grant select on table public.advanced_preliminary_case_reports to service_role;
grant select on table public.advanced_preliminary_meaning_units to service_role;
grant select on table public.advanced_preliminary_codes to service_role;
grant select on table public.advanced_preliminary_code_meaning_units to service_role;
grant select on table public.advanced_preliminary_categories to service_role;
grant select on table public.advanced_preliminary_category_codes to service_role;

revoke all on function public.refresh_advanced_preliminary_analysis_run(uuid) from public, anon, authenticated;
revoke all on function public.create_advanced_preliminary_analysis_run(text, text, text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.claim_next_advanced_preliminary_analysis() from public, anon, authenticated;
revoke all on function public.complete_advanced_preliminary_analysis(uuid, text, text, integer, integer, jsonb) from public, anon, authenticated;
revoke all on function public.fail_advanced_preliminary_analysis(uuid, text, boolean) from public, anon, authenticated;

grant execute on function public.refresh_advanced_preliminary_analysis_run(uuid) to service_role;
grant execute on function public.create_advanced_preliminary_analysis_run(text, text, text, text, text, text, text) to service_role;
grant execute on function public.claim_next_advanced_preliminary_analysis() to service_role;
grant execute on function public.complete_advanced_preliminary_analysis(uuid, text, text, integer, integer, jsonb) to service_role;
grant execute on function public.fail_advanced_preliminary_analysis(uuid, text, boolean) to service_role;
