create table public.participant_code_map (
    code_number bigint generated by default as identity primary key,
    participant_id text not null unique,
    participant_code text generated always as (
        'P' || lpad(code_number::text, 4, '0')
    ) stored unique,
    created_at timestamptz not null default now(),
    constraint participant_code_map_participant_id_not_blank
        check (btrim(participant_id) <> ''),
    constraint participant_code_map_code_format
        check (participant_code ~ '^P[0-9]{4,}$')
);

comment on table public.participant_code_map is
    'Private stable mapping between source participant identifiers and researcher-facing participant codes. The mapping is not rendered as a dashboard list.';

comment on column public.participant_code_map.participant_code is
    'Stable researcher-facing code such as P0001; source participant identifiers remain available only in verified transcript identity details.';

with participant_first_seen as (
    select
        participant_id,
        min(first_seen) as first_seen
    from (
        select
            nullif(btrim(participant_id), '') as participant_id,
            min(created_at) as first_seen
        from public.interview_sessions
        group by nullif(btrim(participant_id), '')

        union all

        select
            nullif(btrim("Participant"), '') as participant_id,
            min("Timestamp") as first_seen
        from public.interview_messages
        group by nullif(btrim("Participant"), '')
    ) participants
    where participant_id is not null
    group by participant_id
), numbered_participants as (
    select
        row_number() over (
            order by first_seen nulls last, participant_id
        ) as code_number,
        participant_id
    from participant_first_seen
)
insert into public.participant_code_map (code_number, participant_id)
select code_number, participant_id
from numbered_participants
order by code_number;

select setval(
    pg_get_serial_sequence(
        'public.participant_code_map',
        'code_number'
    ),
    greatest(
        coalesce((select max(code_number) from public.participant_code_map), 0),
        1
    ),
    exists(select 1 from public.participant_code_map)
);

alter table public.participant_code_map enable row level security;

revoke all on table public.participant_code_map
from public, anon, authenticated, service_role;

revoke all on sequence public.participant_code_map_code_number_seq
from public, anon, authenticated, service_role;

grant select, insert on table public.participant_code_map
to service_role;

grant usage, select on sequence public.participant_code_map_code_number_seq
to service_role;

create or replace function public.ensure_participant_code_mapping()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    insert into public.participant_code_map (participant_id)
    values (new.participant_id)
    on conflict (participant_id) do nothing;

    return new;
end;
$$;

revoke all on function public.ensure_participant_code_mapping()
from public, anon, authenticated, service_role;

create trigger interview_sessions_ensure_participant_code
after insert or update of participant_id on public.interview_sessions
for each row
execute function public.ensure_participant_code_mapping();
